// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

package vec

//go:noescape
func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func addWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)

//go:noescape
func subWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func addScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)

//go:noescape
func subScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func negToAVX512(vOut []uint64, v []uint64, q uint64)

//go:noescape
func negWordToAVX512(vOut []uint64, v []uint64)

//go:noescape
func mulScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulAddScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func mulSubScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)

//go:noescape
func sMulScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulAddScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func sMulSubScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)

//go:noescape
func mulWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulAddWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func mulSubWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)

//go:noescape
func sMulToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulAddLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func sMulSubLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)

//go:noescape
func fMulToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func fMulAddToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)

//go:noescape
func fMulSubToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
