// Code generated by command: go run asmgen.go -vec -out ../../math/vec/asm_mod_amd64.s -stubs ../../math/vec/asm_mod_stub_amd64.go -pkg=vec. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

DATA MASK_LO<>+0(SB)/8, $0x00000000ffffffff
GLOBL MASK_LO<>(SB), RODATA|NOPTR, $8

DATA MASK_52<>+0(SB)/8, $0x000fffffffffffff
GLOBL MASK_52<>(SB), RODATA|NOPTR, $8

// func addToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·addToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z1
	VMOVDQU64 (SI)(R8*8), Z2
	VPADDQ    Z2, Z1, Z1
	VPSUBQ    Z0, Z1, Z2
	VPMINUQ   Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	ADDQ    R9, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512F
TEXT ·addWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPADDQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	ADDQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·subToAVX512(SB), NOSPLIT, $0-80
	MOVQ         q+72(FP), AX
	VPBROADCASTQ q+72(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v0_base+24(FP), BX
	MOVQ         v1_base+48(FP), SI
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z1
	VMOVDQU64 (SI)(R8*8), Z2
	VPSUBQ    Z2, Z1, Z1
	VPADDQ    Z0, Z1, Z2
	VPMINUQ   Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	MOVQ    (SI)(R8*8), R9
	SUBQ    R9, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512F
TEXT ·subWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	MOVQ (BX)(DI*8), R8
	SUBQ R8, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func addScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·addScalarToAVX512(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Z1
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z2
	VPADDQ    Z1, Z2, Z2
	VPSUBQ    Z0, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	ADDQ    SI, DI
	MOVQ    DI, R9
	SUBQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func addScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512F
TEXT ·addScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         AX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z1
	VPADDQ    Z0, Z1, Z1
	VMOVDQU64 Z1, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	ADDQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func subScalarToAVX512(vOut []uint64, v []uint64, c uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·subScalarToAVX512(SB), NOSPLIT, $0-64
	MOVQ         q+56(FP), AX
	VPBROADCASTQ q+56(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         c+48(FP), SI
	VPBROADCASTQ c+48(FP), Z1
	MOVQ         CX, DI
	SHRQ         $0x03, DI
	SHLQ         $0x03, DI
	XORQ         R8, R8
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(R8*8), Z2
	VPSUBQ    Z1, Z2, Z2
	VPADDQ    Z0, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (DX)(R8*8)
	ADDQ      $0x08, R8

loop_end:
	CMPQ R8, DI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(R8*8), DI
	SUBQ    SI, DI
	MOVQ    DI, R9
	ADDQ    AX, R9
	CMPQ    AX, DI
	CMOVQLS R9, DI
	MOVQ    DI, (DX)(R8*8)
	ADDQ    $0x01, R8

leftover_loop_end:
	CMPQ R8, CX
	JL   leftover_loop_body
	RET

// func subScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512F
TEXT ·subScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v_base+24(FP), DX
	MOVQ         c+48(FP), BX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         AX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z1
	VPSUBQ    Z0, Z1, Z1
	VMOVDQU64 Z1, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(DI*8), SI
	SUBQ BX, SI
	MOVQ SI, (CX)(DI*8)
	ADDQ $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func negToAVX512(vOut []uint64, v []uint64, q uint64)
// Requires: AVX512F, CMOV
TEXT ·negToAVX512(SB), NOSPLIT, $0-56
	MOVQ         q+48(FP), AX
	VPBROADCASTQ q+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPSUBQ    Z1, Z0, Z1
	VPCMPQ    $0x04, Z1, Z0, K1
	VMOVAPD.Z Z1, K1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (BX)(DI*8), SI
	CMPQ    SI, $0x00
	CMOVQEQ AX, SI
	NEGQ    SI
	ADDQ    AX, SI
	MOVQ    SI, (DX)(DI*8)
	ADDQ    $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func negWordToAVX512(vOut []uint64, v []uint64)
// Requires: AVX512F
TEXT ·negWordToAVX512(SB), NOSPLIT, $0-48
	VPXORQ Z0, Z0, Z0
	MOVQ   vOut_len+8(FP), AX
	MOVQ   vOut_base+0(FP), CX
	MOVQ   v_base+24(FP), DX
	MOVQ   AX, BX
	SHRQ   $0x03, BX
	SHLQ   $0x03, BX
	XORQ   SI, SI
	JMP    loop_end

loop_body:
	VMOVDQU64 (DX)(SI*8), Z1
	VPSUBQ    Z1, Z0, Z1
	VMOVDQU64 Z1, (CX)(SI*8)
	ADDQ      $0x08, SI

loop_end:
	CMPQ SI, BX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ (DX)(SI*8), BX
	NEGQ BX
	MOVQ BX, (CX)(SI*8)
	ADDQ $0x01, SI

leftover_loop_end:
	CMPQ SI, AX
	JL   leftover_loop_body
	RET

// func mulScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  SI, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulAddScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulAddScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z2
	VMOVDQU64 (DX)(DI*8), Z1
	VPADDQ    Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func mulSubScalarWordToAVX512(vOut []uint64, v []uint64, c uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulSubScalarWordToAVX512(SB), NOSPLIT, $0-56
	MOVQ         c+48(FP), AX
	VPBROADCASTQ c+48(FP), Z0
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), DX
	MOVQ         v_base+24(FP), BX
	MOVQ         CX, SI
	SHRQ         $0x03, SI
	SHLQ         $0x03, SI
	XORQ         DI, DI
	JMP          loop_end

loop_body:
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z1, Z0, Z2
	VMOVDQU64 (DX)(DI*8), Z1
	VPSUBQ    Z2, Z1, Z1
	VMOVDQU64 Z1, (DX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (BX)(DI*8), SI
	IMULQ AX, SI
	MOVQ  (DX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (DX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, CX
	JL   leftover_loop_body
	RET

// func sMulScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   Z6, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulAddScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPADDQ      Z6, Z5, Z5
	VPSUBQ      Z2, Z5, Z8
	VPMINUQ     Z8, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulSubScalarToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z5
	VPMINUQ     Z5, Z6, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPSUBQ      Z6, Z5, Z5
	VPADDQ      Z2, Z5, Z8
	VPMINUQ     Z8, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulScalarLazyToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   Z6, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  R10, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulAddScalarLazyToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPADDQ      Z6, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  (DI)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarLazyToAVX512IFMA(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulSubScalarLazyToAVX512IFMA(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z2
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z3
	VPBROADCASTQ cS+56(FP), Z4
	VPSRLQ       $0x0c, Z4, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (R8)(R9*8), Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z5, Z4, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z5, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   (DI)(R9*8), Z5
	VPADDQ      Z6, Z5, Z5
	VMOVDQU64   Z5, (DI)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  (DI)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 Z5, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulAddScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPADDQ    Z5, Z6, Z6
	VPSUBQ    Z1, Z6, Z5
	VPMINUQ   Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulSubScalarToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VPSUBQ    Z1, Z5, Z6
	VPMINUQ   Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPSUBQ    Z5, Z6, Z6
	VPADDQ    Z1, Z6, Z5
	VPMINUQ   Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (R8)(R9*8), R10
	MOVQ    BX, DX
	MULXQ   R10, DX, R11
	IMULQ   AX, R11
	IMULQ   CX, R10
	SUBQ    R11, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (DI)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (DI)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulScalarLazyToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VMOVDQU64 Z5, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  R10, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulAddScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulAddScalarLazyToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPADDQ    Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  (DI)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func sMulSubScalarLazyToAVX512(vOut []uint64, v []uint64, c uint64, cS uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulSubScalarLazyToAVX512(SB), NOSPLIT, $0-72
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+64(FP), AX
	VPBROADCASTQ q+64(FP), Z1
	MOVQ         c+48(FP), CX
	MOVQ         cS+56(FP), BX
	VPBROADCASTQ c+48(FP), Z2
	VPBROADCASTQ cS+56(FP), Z3
	VPSRLQ       $0x20, Z3, Z4
	MOVQ         vOut_len+8(FP), SI
	MOVQ         vOut_base+0(FP), DI
	MOVQ         v_base+24(FP), R8
	MOVQ         SI, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (R8)(R9*8), Z5
	VPSRLQ    $0x20, Z5, Z6
	VPMULUDQ  Z3, Z5, Z7
	VPMULUDQ  Z4, Z5, Z8
	VPMULUDQ  Z3, Z6, Z9
	VPMULUDQ  Z4, Z6, Z6
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z7
	VPANDQ    Z0, Z7, Z8
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPADDQ    Z8, Z9, Z7
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z6, Z7, Z6
	VPMULLQ   Z6, Z1, Z6
	VPMULLQ   Z5, Z2, Z5
	VPSUBQ    Z6, Z5, Z5
	VMOVDQU64 (DI)(R9*8), Z6
	VPADDQ    Z5, Z6, Z6
	VMOVDQU64 Z6, (DI)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (R8)(R9*8), R10
	MOVQ  BX, DX
	MULXQ R10, DX, R11
	IMULQ AX, R11
	IMULQ CX, R10
	SUBQ  R11, R10
	MOVQ  (DI)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (DI)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, SI
	JL   leftover_loop_body
	RET

// func mulWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  SI, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulAddWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulAddWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z1
	VMOVDQU64 (CX)(DI*8), Z0
	VPADDQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	ADDQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func mulSubWordToAVX512(vOut []uint64, v0 []uint64, v1 []uint64)
// Requires: AVX512DQ, AVX512F
TEXT ·mulSubWordToAVX512(SB), NOSPLIT, $0-72
	MOVQ vOut_len+8(FP), AX
	MOVQ vOut_base+0(FP), CX
	MOVQ v0_base+24(FP), DX
	MOVQ v1_base+48(FP), BX
	MOVQ AX, SI
	SHRQ $0x03, SI
	SHLQ $0x03, SI
	XORQ DI, DI
	JMP  loop_end

loop_body:
	VMOVDQU64 (DX)(DI*8), Z0
	VMOVDQU64 (BX)(DI*8), Z1
	VPMULLQ   Z0, Z1, Z1
	VMOVDQU64 (CX)(DI*8), Z0
	VPSUBQ    Z1, Z0, Z0
	VMOVDQU64 Z0, (CX)(DI*8)
	ADDQ      $0x08, DI

loop_end:
	CMPQ DI, SI
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (DX)(DI*8), SI
	MOVQ  (BX)(DI*8), R8
	IMULQ R8, SI
	MOVQ  (CX)(DI*8), R8
	SUBQ  SI, R8
	MOVQ  R8, (CX)(DI*8)
	ADDQ  $0x01, DI

leftover_loop_end:
	CMPQ DI, AX
	JL   leftover_loop_body
	RET

// func sMulToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   Z6, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulAddToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPADDQ      Z6, Z3, Z3
	VPSUBQ      Z2, Z3, Z4
	VPMINUQ     Z4, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2, CMOV
TEXT ·sMulSubToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VPSUBQ      Z2, Z6, Z3
	VPMINUQ     Z3, Z6, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPSUBQ      Z6, Z3, Z3
	VPADDQ      Z2, Z3, Z4
	VPMINUQ     Z4, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulLazyToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   Z6, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  R10, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulAddLazyToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPADDQ      Z6, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  (BX)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubLazyToAVX512IFMA(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512F, AVX512IFMA, BMI2
TEXT ·sMulSubLazyToAVX512IFMA(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_52<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z2
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64   (SI)(R9*8), Z3
	VMOVDQU64   (DI)(R9*8), Z4
	VMOVDQU64   (R8)(R9*8), Z5
	VPSUBQ      Z3, Z2, Z3
	VPSRLQ      $0x0c, Z5, Z5
	VPXORQ      Z7, Z7, Z7
	VPMADD52HUQ Z3, Z5, Z7
	VPXORQ      Z6, Z6, Z6
	VPMADD52LUQ Z2, Z7, Z6
	VPSUBQ      Z6, Z1, Z6
	VPMADD52LUQ Z4, Z3, Z6
	VPANDQ      Z6, Z0, Z6
	VMOVDQU64   (BX)(R9*8), Z3
	VPADDQ      Z6, Z3, Z3
	VMOVDQU64   Z3, (BX)(R9*8)
	ADDQ        $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	SUBQ  AX, R10
	NEGQ  R10
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  (BX)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 Z2, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    R10, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulAddToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPADDQ    Z2, Z3, Z3
	VPSUBQ    Z1, Z3, Z2
	VPMINUQ   Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	ADDQ    R10, DX
	MOVQ    DX, R10
	SUBQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2, CMOV
TEXT ·sMulSubToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VPSUBQ    Z1, Z2, Z3
	VPMINUQ   Z3, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPSUBQ    Z2, Z3, Z3
	VPADDQ    Z1, Z3, Z2
	VPMINUQ   Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ    (SI)(R9*8), R10
	MOVQ    (DI)(R9*8), R11
	MOVQ    (R8)(R9*8), DX
	MULXQ   R10, DX, R12
	IMULQ   AX, R12
	IMULQ   R11, R10
	SUBQ    R12, R10
	MOVQ    R10, DX
	SUBQ    AX, DX
	CMPQ    AX, R10
	CMOVQLS DX, R10
	MOVQ    (BX)(R9*8), DX
	SUBQ    R10, DX
	MOVQ    DX, R10
	ADDQ    AX, R10
	CMPQ    AX, DX
	CMOVQLS R10, DX
	MOVQ    DX, (BX)(R9*8)
	ADDQ    $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulLazyToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VMOVDQU64 Z2, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  R10, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulAddLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulAddLazyToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPADDQ    Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  (BX)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func sMulSubLazyToAVX512(vOut []uint64, v0 []uint64, v1 []uint64, v1S []uint64, q uint64)
// Requires: AVX512DQ, AVX512F, BMI2
TEXT ·sMulSubLazyToAVX512(SB), NOSPLIT, $0-104
	VPBROADCASTQ MASK_LO<>+0(SB), Z0
	VPXORQ       Z1, Z1, Z1
	MOVQ         q+96(FP), AX
	VPBROADCASTQ q+96(FP), Z1
	MOVQ         vOut_len+8(FP), CX
	MOVQ         vOut_base+0(FP), BX
	MOVQ         v0_base+24(FP), SI
	MOVQ         v1_base+48(FP), DI
	MOVQ         v1S_base+72(FP), R8
	MOVQ         CX, DX
	SHRQ         $0x03, DX
	SHLQ         $0x03, DX
	XORQ         R9, R9
	JMP          loop_end

loop_body:
	VMOVDQU64 (SI)(R9*8), Z2
	VMOVDQU64 (DI)(R9*8), Z3
	VMOVDQU64 (R8)(R9*8), Z4
	VPSUBQ    Z2, Z1, Z2
	VPSRLQ    $0x20, Z2, Z5
	VPSRLQ    $0x20, Z4, Z6
	VPMULUDQ  Z4, Z2, Z7
	VPMULUDQ  Z6, Z2, Z8
	VPMULUDQ  Z4, Z5, Z4
	VPMULUDQ  Z6, Z5, Z5
	VPSRLQ    $0x20, Z7, Z7
	VPADDQ    Z7, Z8, Z6
	VPANDQ    Z0, Z6, Z7
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPADDQ    Z7, Z4, Z6
	VPSRLQ    $0x20, Z6, Z6
	VPADDQ    Z5, Z6, Z5
	VPMULLQ   Z5, Z1, Z5
	VPMULLQ   Z2, Z3, Z2
	VPSUBQ    Z5, Z2, Z2
	VMOVDQU64 (BX)(R9*8), Z3
	VPADDQ    Z2, Z3, Z3
	VMOVDQU64 Z3, (BX)(R9*8)
	ADDQ      $0x08, R9

loop_end:
	CMPQ R9, DX
	JL   loop_body
	JMP  leftover_loop_end

leftover_loop_body:
	MOVQ  (SI)(R9*8), R10
	MOVQ  (DI)(R9*8), R11
	MOVQ  (R8)(R9*8), DX
	SUBQ  AX, R10
	NEGQ  R10
	MULXQ R10, DX, R12
	IMULQ AX, R12
	IMULQ R11, R10
	SUBQ  R12, R10
	MOVQ  (BX)(R9*8), DX
	ADDQ  R10, DX
	MOVQ  DX, (BX)(R9*8)
	ADDQ  $0x01, R9

leftover_loop_end:
	CMPQ R9, CX
	JL   leftover_loop_body
	RET

// func fMulToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F
TEXT ·fMulToAVX512F(SB), NOSPLIT, $0-96
	VPXORQ       Z0, Z0, Z0
	VPBROADCASTQ q+72(FP), Z1
	VPBROADCASTQ qf+80(FP), Z1
	VPBROADCASTQ qfInv+88(FP), Z2
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	SHRQ         $0x03, AX
	SHLQ         $0x03, AX
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU64         (DX)(SI*8), Z3
	VMOVDQU64         (BX)(SI*8), Z4
	VCVTUQQ2PD.RU_SAE Z3, Z3
	VCVTUQQ2PD.RU_SAE Z4, Z4
	VMULPD            Z3, Z4, Z5
	VMOVAPD           Z5, Z6
	VFMSUB231PD       Z3, Z4, Z6
	VMULPD            Z5, Z2, Z3
	VRNDSCALEPD       $0x01, Z3, Z3
	VMOVAPD           Z5, Z4
	VFNMADD231PD      Z3, Z1, Z4
	VADDPD            Z4, Z6, Z3
	VCMPPD            $0x11, Z0, Z3, K1
	VADDPD            Z3, Z1, K1, Z3
	VCVTPD2UQQ.RU_SAE Z3, Z3
	VMOVDQU64         Z3, (CX)(SI*8)
	ADDQ              $0x08, SI

loop_end:
	CMPQ SI, AX
	JL   loop_body
	RET

// func fMulAddToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F
TEXT ·fMulAddToAVX512F(SB), NOSPLIT, $0-96
	VPXORQ       Z0, Z0, Z0
	VPBROADCASTQ q+72(FP), Z1
	VPBROADCASTQ qf+80(FP), Z2
	VPBROADCASTQ qfInv+88(FP), Z3
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	SHRQ         $0x03, AX
	SHLQ         $0x03, AX
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU64         (DX)(SI*8), Z4
	VMOVDQU64         (BX)(SI*8), Z5
	VCVTUQQ2PD.RU_SAE Z4, Z4
	VCVTUQQ2PD.RU_SAE Z5, Z5
	VMULPD            Z4, Z5, Z6
	VMOVAPD           Z6, Z7
	VFMSUB231PD       Z4, Z5, Z7
	VMULPD            Z6, Z3, Z4
	VRNDSCALEPD       $0x01, Z4, Z4
	VMOVAPD           Z6, Z5
	VFNMADD231PD      Z4, Z2, Z5
	VADDPD            Z5, Z7, Z5
	VCMPPD            $0x11, Z0, Z5, K1
	VADDPD            Z5, Z2, K1, Z5
	VCVTPD2UQQ.RU_SAE Z5, Z5
	VMOVDQU64         (CX)(SI*8), Z4
	VPADDQ            Z5, Z4, Z4
	VPSUBQ            Z1, Z4, Z5
	VPMINUQ           Z5, Z4, Z4
	VMOVDQU64         Z4, (CX)(SI*8)
	ADDQ              $0x08, SI

loop_end:
	CMPQ SI, AX
	JL   loop_body
	RET

// func fMulSubToAVX512F(vOut []uint64, v0 []uint64, v1 []uint64, q uint64, qf float64, qfInv float64)
// Requires: AVX512DQ, AVX512F
TEXT ·fMulSubToAVX512F(SB), NOSPLIT, $0-96
	VPXORQ       Z0, Z0, Z0
	VPBROADCASTQ q+72(FP), Z1
	VPBROADCASTQ qf+80(FP), Z2
	VPBROADCASTQ qfInv+88(FP), Z3
	MOVQ         vOut_len+8(FP), AX
	MOVQ         vOut_base+0(FP), CX
	MOVQ         v0_base+24(FP), DX
	MOVQ         v1_base+48(FP), BX
	SHRQ         $0x03, AX
	SHLQ         $0x03, AX
	XORQ         SI, SI
	JMP          loop_end

loop_body:
	VMOVDQU64         (DX)(SI*8), Z4
	VMOVDQU64         (BX)(SI*8), Z5
	VCVTUQQ2PD.RU_SAE Z4, Z4
	VCVTUQQ2PD.RU_SAE Z5, Z5
	VMULPD            Z4, Z5, Z6
	VMOVAPD           Z6, Z7
	VFMSUB231PD       Z4, Z5, Z7
	VMULPD            Z6, Z3, Z4
	VRNDSCALEPD       $0x01, Z4, Z4
	VMOVAPD           Z6, Z5
	VFNMADD231PD      Z4, Z2, Z5
	VADDPD            Z5, Z7, Z5
	VCMPPD            $0x11, Z0, Z5, K1
	VADDPD            Z5, Z2, K1, Z5
	VCVTPD2UQQ.RU_SAE Z5, Z5
	VMOVDQU64         (CX)(SI*8), Z4
	VPSUBQ            Z5, Z4, Z4
	VPADDQ            Z1, Z4, Z5
	VPMINUQ           Z5, Z4, Z4
	VMOVDQU64         Z4, (CX)(SI*8)
	ADDQ              $0x08, SI

loop_end:
	CMPQ SI, AX
	JL   loop_body
	RET
