// Code generated by gnark-crypto/generator. DO NOT EDIT.
#include "textflag.h"
#include "funcdata.h"
#include "go_asm.h"

#define REDUCE(ra0, ra1, ra2, ra3, ra4, ra5, ra6, rb0, rb1, rb2, rb3, rb4, rb5, rb6, q0, q1, q2, q3, q4, q5, q6) \
	MOVQ    ra0, rb0; \
	SUBQ    q0, ra0;  \
	MOVQ    ra1, rb1; \
	SBBQ    q1, ra1;  \
	MOVQ    ra2, rb2; \
	SBBQ    q2, ra2;  \
	MOVQ    ra3, rb3; \
	SBBQ    q3, ra3;  \
	MOVQ    ra4, rb4; \
	SBBQ    q4, ra4;  \
	MOVQ    ra5, rb5; \
	SBBQ    q5, ra5;  \
	MOVQ    ra6, rb6; \
	SBBQ    q6, ra6;  \
	CMOVQCS rb0, ra0; \
	CMOVQCS rb1, ra1; \
	CMOVQCS rb2, ra2; \
	CMOVQCS rb3, ra3; \
	CMOVQCS rb4, ra4; \
	CMOVQCS rb5, ra5; \
	CMOVQCS rb6, ra6; \

TEXT ·reduce(SB), $16-8
	MOVQ res+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	RET

// MulBy3(x *Element)
TEXT ·MulBy3(SB), $16-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9
	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX
	ADCQ 16(AX), BX
	ADCQ 24(AX), SI
	ADCQ 32(AX), DI
	ADCQ 40(AX), R8
	ADCQ 48(AX), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	RET

// MulBy5(x *Element)
TEXT ·MulBy5(SB), $16-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9
	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX
	ADCQ 16(AX), BX
	ADCQ 24(AX), SI
	ADCQ 32(AX), DI
	ADCQ 40(AX), R8
	ADCQ 48(AX), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	RET

// MulBy13(x *Element)
TEXT ·MulBy13(SB), $72-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9
	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (s2-24(SP),s3-32(SP),s4-40(SP),s5-48(SP),s6-56(SP),s7-64(SP),s8-72(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,s2-24(SP),s3-32(SP),s4-40(SP),s5-48(SP),s6-56(SP),s7-64(SP),s8-72(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ DX, s2-24(SP)
	MOVQ CX, s3-32(SP)
	MOVQ BX, s4-40(SP)
	MOVQ SI, s5-48(SP)
	MOVQ DI, s6-56(SP)
	MOVQ R8, s7-64(SP)
	MOVQ R9, s8-72(SP)
	ADDQ DX, DX
	ADCQ CX, CX
	ADCQ BX, BX
	ADCQ SI, SI
	ADCQ DI, DI
	ADCQ R8, R8
	ADCQ R9, R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ s2-24(SP), DX
	ADCQ s3-32(SP), CX
	ADCQ s4-40(SP), BX
	ADCQ s5-48(SP), SI
	ADCQ s6-56(SP), DI
	ADCQ s7-64(SP), R8
	ADCQ s8-72(SP), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX
	ADCQ 16(AX), BX
	ADCQ 24(AX), SI
	ADCQ 32(AX), DI
	ADCQ 40(AX), R8
	ADCQ 48(AX), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	RET

// Butterfly(a, b *Element) sets a = a + b; b = a - b
TEXT ·Butterfly(SB), $16-16
	MOVQ b+8(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9
	MOVQ a+0(FP), AX
	ADDQ 0(AX), DX
	ADCQ 8(AX), CX
	ADCQ 16(AX), BX
	ADCQ 24(AX), SI
	ADCQ 32(AX), DI
	ADCQ 40(AX), R8
	ADCQ 48(AX), R9
	MOVQ DX, R10
	MOVQ CX, R11
	MOVQ BX, R12
	MOVQ SI, R13
	MOVQ DI, R14
	MOVQ R8, s0-8(SP)
	MOVQ R9, s1-16(SP)
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	MOVQ 16(AX), BX
	MOVQ 24(AX), SI
	MOVQ 32(AX), DI
	MOVQ 40(AX), R8
	MOVQ 48(AX), R9
	MOVQ b+8(FP), AX
	SUBQ 0(AX), DX
	SBBQ 8(AX), CX
	SBBQ 16(AX), BX
	SBBQ 24(AX), SI
	SBBQ 32(AX), DI
	SBBQ 40(AX), R8
	SBBQ 48(AX), R9
	JCC  noReduce_1
	MOVQ $const_q0, AX
	ADDQ AX, DX
	MOVQ $const_q1, AX
	ADCQ AX, CX
	MOVQ $const_q2, AX
	ADCQ AX, BX
	MOVQ $const_q3, AX
	ADCQ AX, SI
	MOVQ $const_q4, AX
	ADCQ AX, DI
	MOVQ $const_q5, AX
	ADCQ AX, R8
	MOVQ $const_q6, AX
	ADCQ AX, R9

noReduce_1:
	MOVQ b+8(FP), AX
	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	MOVQ R10, DX
	MOVQ R11, CX
	MOVQ R12, BX
	MOVQ R13, SI
	MOVQ R14, DI
	MOVQ s0-8(SP), R8
	MOVQ s1-16(SP), R9

	// reduce element(DX,CX,BX,SI,DI,R8,R9) using temp registers (R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP))
	REDUCE(DX,CX,BX,SI,DI,R8,R9,R10,R11,R12,R13,R14,s0-8(SP),s1-16(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ a+0(FP), AX
	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	MOVQ BX, 16(AX)
	MOVQ SI, 24(AX)
	MOVQ DI, 32(AX)
	MOVQ R8, 40(AX)
	MOVQ R9, 48(AX)
	RET

// mul(res, x, y *Element)
TEXT ·mul(SB), $24-24

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521
	// See github.com/Consensys/gnark-crypto/field/generator for more comments.

	NO_LOCAL_POINTERS
	CMPB ·supportAdx(SB), $1
	JNE  noAdx_2
	MOVQ x+8(FP), R9

	// x -> R11
	MOVQ 0(R9), R11
	MOVQ y+16(FP), R12

	// A -> BP
	// t[0] -> R14
	// t[1] -> R13
	// t[2] -> CX
	// t[3] -> BX
	// t[4] -> SI
	// t[5] -> DI
	// t[6] -> R8
#define MACC(in0, in1, in2) \
	ADCXQ in0, in1     \
	MULXQ in2, AX, in0 \
	ADOXQ AX, in1      \

#define DIV_SHIFT() \
	MOVQ  $const_qInvNeg, DX        \
	IMULQ R14, DX                   \
	XORQ  AX, AX                    \
	MULXQ ·qElement+0(SB), AX, R10  \
	ADCXQ R14, AX                   \
	MOVQ  R10, R14                  \
	MACC(R13, R14, ·qElement+8(SB)) \
	MACC(CX, R13, ·qElement+16(SB)) \
	MACC(BX, CX, ·qElement+24(SB))  \
	MACC(SI, BX, ·qElement+32(SB))  \
	MACC(DI, SI, ·qElement+40(SB))  \
	MACC(R8, DI, ·qElement+48(SB))  \
	MOVQ  $0, AX                    \
	ADCXQ AX, R8                    \
	ADOXQ BP, R8                    \

#define MUL_WORD_0() \
	XORQ  AX, AX         \
	MULXQ R11, R14, R13  \
	MULXQ 8(R9), AX, CX  \
	ADOXQ AX, R13        \
	MULXQ 16(R9), AX, BX \
	ADOXQ AX, CX         \
	MULXQ 24(R9), AX, SI \
	ADOXQ AX, BX         \
	MULXQ 32(R9), AX, DI \
	ADOXQ AX, SI         \
	MULXQ 40(R9), AX, R8 \
	ADOXQ AX, DI         \
	MULXQ 48(R9), AX, BP \
	ADOXQ AX, R8         \
	MOVQ  $0, AX         \
	ADOXQ AX, BP         \
	DIV_SHIFT()          \

#define MUL_WORD_N() \
	XORQ  AX, AX         \
	MULXQ R11, AX, BP    \
	ADOXQ AX, R14        \
	MACC(BP, R13, 8(R9)) \
	MACC(BP, CX, 16(R9)) \
	MACC(BP, BX, 24(R9)) \
	MACC(BP, SI, 32(R9)) \
	MACC(BP, DI, 40(R9)) \
	MACC(BP, R8, 48(R9)) \
	MOVQ  $0, AX         \
	ADCXQ AX, BP         \
	ADOXQ AX, BP         \
	DIV_SHIFT()          \

	// mul body
	MOVQ 0(R12), DX
	MUL_WORD_0()
	MOVQ 8(R12), DX
	MUL_WORD_N()
	MOVQ 16(R12), DX
	MUL_WORD_N()
	MOVQ 24(R12), DX
	MUL_WORD_N()
	MOVQ 32(R12), DX
	MUL_WORD_N()
	MOVQ 40(R12), DX
	MUL_WORD_N()
	MOVQ 48(R12), DX
	MUL_WORD_N()

	// reduce element(R14,R13,CX,BX,SI,DI,R8) using temp registers (R10,R9,R12,R11,AX,DX,s0-8(SP))
	REDUCE(R14,R13,CX,BX,SI,DI,R8,R10,R9,R12,R11,AX,DX,s0-8(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ res+0(FP), AX
	MOVQ R14, 0(AX)
	MOVQ R13, 8(AX)
	MOVQ CX, 16(AX)
	MOVQ BX, 24(AX)
	MOVQ SI, 32(AX)
	MOVQ DI, 40(AX)
	MOVQ R8, 48(AX)
	RET

noAdx_2:
	MOVQ res+0(FP), AX
	MOVQ AX, (SP)
	MOVQ x+8(FP), AX
	MOVQ AX, 8(SP)
	MOVQ y+16(FP), AX
	MOVQ AX, 16(SP)
	CALL ·_mulGeneric(SB)
	RET

TEXT ·fromMont(SB), $8-8
	NO_LOCAL_POINTERS

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521
	// when y = 1 we have:
	// for i=0 to N-1
	// 		t[i] = x[i]
	// for i=0 to N-1
	// 		m := t[0]*q'[0] mod W
	// 		C,_ := t[0] + m*q[0]
	// 		for j=1 to N-1
	// 		    (C,t[j-1]) := t[j] + m*q[j] + C
	// 		t[N-1] = C
	CMPB ·supportAdx(SB), $1
	JNE  noAdx_3
	MOVQ res+0(FP), DX
	MOVQ 0(DX), R13
	MOVQ 8(DX), R14
	MOVQ 16(DX), CX
	MOVQ 24(DX), BX
	MOVQ 32(DX), SI
	MOVQ 40(DX), DI
	MOVQ 48(DX), R8
	XORQ DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13

	// (C,t[1]) := t[2] + m*q[2] + C
	ADCXQ CX, R14
	MULXQ ·qElement+16(SB), AX, CX
	ADOXQ AX, R14

	// (C,t[2]) := t[3] + m*q[3] + C
	ADCXQ BX, CX
	MULXQ ·qElement+24(SB), AX, BX
	ADOXQ AX, CX

	// (C,t[3]) := t[4] + m*q[4] + C
	ADCXQ SI, BX
	MULXQ ·qElement+32(SB), AX, SI
	ADOXQ AX, BX

	// (C,t[4]) := t[5] + m*q[5] + C
	ADCXQ DI, SI
	MULXQ ·qElement+40(SB), AX, DI
	ADOXQ AX, SI

	// (C,t[5]) := t[6] + m*q[6] + C
	ADCXQ R8, DI
	MULXQ ·qElement+48(SB), AX, R8
	ADOXQ AX, DI
	MOVQ  $0, AX
	ADCXQ AX, R8
	ADOXQ AX, R8

	// reduce element(R13,R14,CX,BX,SI,DI,R8) using temp registers (R9,R10,R11,R12,DX,AX,s0-8(SP))
	REDUCE(R13,R14,CX,BX,SI,DI,R8,R9,R10,R11,R12,DX,AX,s0-8(SP),·qElement+0(SB),·qElement+8(SB),·qElement+16(SB),·qElement+24(SB),·qElement+32(SB),·qElement+40(SB),·qElement+48(SB))

	MOVQ res+0(FP), AX
	MOVQ R13, 0(AX)
	MOVQ R14, 8(AX)
	MOVQ CX, 16(AX)
	MOVQ BX, 24(AX)
	MOVQ SI, 32(AX)
	MOVQ DI, 40(AX)
	MOVQ R8, 48(AX)
	RET

noAdx_3:
	MOVQ res+0(FP), AX
	MOVQ AX, (SP)
	CALL ·_fromMontGeneric(SB)
	RET
