package main

import (
	"crypto/rand"
	"fmt"
	"math"
	"math/big"
	"time"

	"github.com/sp301415/ringo-snark/buckler"
	"github.com/sp301415/ringo-snark/examples/bfv/zp"
	"github.com/sp301415/ringo-snark/math/bignum"
	"github.com/sp301415/ringo-snark/math/bigpoly"
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	"github.com/tuneinsight/lattigo/v6/schemes/bgv"
)

// In this example, we show how to prove the well-formedness of
// BFV ciphertext generated by lattigo.
//
// Simply, put, for a ciphertext (c0 = -c1*s + (q/t)*m + e, c1), we should prove:
//
// c0 = -c1*s + (q/t)*m + e
// |m| < t
// |e| <= B_e
//
// Where t is the plaintext modulus and B_e is the error bound.
// In our example, we set t = 2^16 + 1.

type CiphertextCircuit[E bignum.Uint[E]] struct {
	NTTChecker buckler.LinearChecker[E]

	Degree           int
	PlaintextModulus uint64
	ErrBound         uint64

	CiphertextNTT [2]buckler.PublicWitness[E]

	SecretKeyNTT buckler.Witness[E]

	Delta         *big.Int
	MessageNTT    buckler.Witness[E]
	MessageCoeffs buckler.Witness[E]

	ErrorNTT    buckler.Witness[E]
	ErrorCoeffs buckler.Witness[E]
}

func (c *CiphertextCircuit[E]) Define(ctx *buckler.Context[E]) {
	// "Empty" element for initialization
	var z E

	ctx.AddLinearConstraint(c.MessageNTT, c.MessageCoeffs, c.NTTChecker)
	ctx.AddLinearConstraint(c.ErrorNTT, c.ErrorCoeffs, c.NTTChecker)

	// Body + Mask * sk - Message - Error = 0
	var ctConstraint buckler.ArithmeticConstraint[E]
	ctConstraint.AddTermWithConst(z.New().SetInt64(1), c.CiphertextNTT[0])
	ctConstraint.AddTermWithConst(z.New().SetInt64(1), c.CiphertextNTT[1], c.SecretKeyNTT)
	ctConstraint.AddTermWithConst(z.New().SetBigInt(new(big.Int).Neg(c.Delta)), nil, c.MessageNTT)
	ctConstraint.AddTermWithConst(z.New().SetInt64(-1), nil, c.ErrorNTT)
	ctx.AddArithmeticConstraint(ctConstraint)

	// |m| < t
	ctx.AddInfNormConstraint(c.MessageCoeffs, c.PlaintextModulus-1)
	// |e| <= B_e
	ctx.AddInfNormConstraint(c.ErrorCoeffs, c.ErrBound)
}

// A common problem of using zk-SNARKs is the mismatch between the constraint space and the proof space.
// Unfortunately, Buckler is not an exception.
// In typical BFV implementations, we use "RNS q", which is a product of word-size primes.
// However, in Buckler, q must be a single, large prime.
//
// To solve this problem, we use modulus switching.
// To be precise, there are two ways.
//
// First way is to generate a ciphertext in RNS q, modulus switch to Buckler q,
// and generate the proof.
// This way, the error bound of fresh ciphertext would be larger,
// so proof size and time would be larger.
//
// Second way is to generate a ciphertext in Buckler q, generate the proof,
// and then modulus switch to RNS q.
// This method has no proof overhead but you should write your own BFV encryption implementation.
//
// In this example, we use the first way.

func main() {
	bfvParamsLiteralLogN13LogQ240 := bgv.ParametersLiteral{
		LogN:             13,
		LogQ:             []int{60, 60, 60, 60},
		PlaintextModulus: (1 << 16) + 1,
	}
	bfvParamsLogN13LogQ240, err := bgv.NewParametersFromLiteral(bfvParamsLiteralLogN13LogQ240)
	if err != nil {
		panic(err)
	}
	ringT := bfvParamsLogN13LogQ240.RingT()
	ringQ := bfvParamsLogN13LogQ240.RingQ()

	// Generate BFV encryption using lattigo.
	keyGen := bgv.NewKeyGenerator(bfvParamsLogN13LogQ240)
	sk := keyGen.GenSecretKeyNew()

	ecd := bgv.NewEncoder(bfvParamsLogN13LogQ240)
	ptT := bfvParamsLogN13LogQ240.RingT().NewPoly()
	ecd.EncodeRingT([]uint64{1, 2, 3, 4}, rlwe.NewScale(1), ptT)
	ptQ := rlwe.NewPlaintext(bfvParamsLogN13LogQ240, bfvParamsLogN13LogQ240.MaxLevel())
	ecd.RingT2Q(bfvParamsLogN13LogQ240.MaxLevel(), true, ptT, ptQ.Value)
	ringQ.NTT(ptQ.Value, ptQ.Value)

	enc := bgv.NewEncryptor(bfvParamsLogN13LogQ240, sk)
	ct, _ := enc.EncryptNew(ptQ)

	// Modulus switch to Buckler q.
	// Note that modulus switching should be done in coefficient representation,
	// So we start by converting them.
	// sk, by default, is in montgomery representation.
	ringQ.IMForm(sk.Value.Q, sk.Value.Q)
	ringQ.INTT(sk.Value.Q, sk.Value.Q)

	// ptT is already in coefficient representation.
	ringQ.INTT(ct.Value[0], ct.Value[0])
	ringQ.INTT(ct.Value[1], ct.Value[1])

	bigringQ := bigpoly.NewCyclotomicEvaluator[*zp.Uint](bfvParamsLogN13LogQ240.N())
	bufBig := make([]*big.Int, bigringQ.Rank())
	for i := range bufBig {
		bufBig[i] = new(big.Int)
	}
	bfvQ := bfvParamsLogN13LogQ240.QBigInt()

	// sk lives in R, so we can simply move it to zp.
	ringQ.PolyToBigintCentered(sk.Value.Q, 1, bufBig)
	skCoeffs := bigringQ.NewPoly(false)
	for i := range bigringQ.Rank() {
		skCoeffs.Coeffs[i].SetBigInt(bufBig[i])
	}
	skNTT := bigringQ.NTT(skCoeffs)

	// ptT lives in R_t, so again we simply move it to zp.
	ringT.PolyToBigintCentered(ptT, 1, bufBig)
	ptCoeffs := bigringQ.NewPoly(false)
	for i := range bigringQ.Rank() {
		ptCoeffs.Coeffs[i].SetBigInt(bufBig[i])
	}
	ptNTT := bigringQ.NTT(ptCoeffs)

	// Finally, we modulus switch the ciphertext.
	ctCoeffs := [2]*bigpoly.Poly[*zp.Uint]{}
	ringQ.PolyToBigintCentered(ct.Value[0], 1, bufBig)
	ctCoeffs[0] = bigringQ.ModSwitch(bufBig, bfvQ)
	ringQ.PolyToBigintCentered(ct.Value[1], 1, bufBig)
	ctCoeffs[1] = bigringQ.ModSwitch(bufBig, bfvQ)
	ctNTT := [2]*bigpoly.Poly[*zp.Uint]{bigringQ.NTT(ctCoeffs[0]), bigringQ.NTT(ctCoeffs[1])}

	// We need to recompute the error so that we can generate aritmetic contraints.
	// Recall that c0 = -c1*s + (q/t)*m + e.
	// So, e = c0 + c1*s - (q/t)*m.
	delta := big.NewInt(0).ModInverse(ringT.Modulus(), ringQ.Modulus())
	// We also modulus switch the scaling factor.
	delta.Mul(delta, zp.Modulus())
	delta.Div(delta, ringQ.Modulus())

	errNTT := bigringQ.NewPoly(true)
	bigringQ.MulTo(errNTT, ctNTT[1], skNTT)
	bigringQ.AddTo(errNTT, errNTT, ctNTT[0])
	bigringQ.ScalarMulSubTo(errNTT, ptNTT, new(zp.Uint).New().SetBigInt(delta))
	errCoeffs := bigringQ.InvNTT(errNTT)

	// After modulus switching, the existing error is replaced by the rounding error,
	// which has infinity norm ~ t + N.
	errBound := uint64(bfvParamsLogN13LogQ240.N()) + bfvParamsLogN13LogQ240.PlaintextModulus()

	// Now we are ready to generate the proof.
	crs := make([]byte, 16)
	rand.Read(crs)

	c := CiphertextCircuit[*zp.Uint]{
		// All non-witness fields should be set for correct compilation.
		NTTChecker: buckler.NewNTTChecker[*zp.Uint](bigringQ.Rank()),

		Degree:           bfvParamsLogN13LogQ240.N(),
		PlaintextModulus: bfvParamsLogN13LogQ240.PlaintextModulus(),
		Delta:            delta,
		ErrBound:         errBound,
	}

	prover, verifier, err := buckler.Compile(bigringQ.Rank(), &c, crs)
	if err != nil {
		panic(err)
	}
	assignment := CiphertextCircuit[*zp.Uint]{
		CiphertextNTT: [2]buckler.PublicWitness[*zp.Uint]{ctNTT[0].Coeffs, ctNTT[1].Coeffs},

		SecretKeyNTT: skNTT.Coeffs,

		MessageNTT:    ptNTT.Coeffs,
		MessageCoeffs: ptCoeffs.Coeffs,

		ErrorNTT:    errNTT.Coeffs,
		ErrorCoeffs: errCoeffs.Coeffs,
	}

	now := time.Now()
	pf, err := prover.Prove(&assignment)
	fmt.Println("Prover time:", time.Since(now))
	if err != nil {
		panic(err)
	}

	publicAssignment := CiphertextCircuit[*zp.Uint]{
		CiphertextNTT: [2]buckler.PublicWitness[*zp.Uint]{ctNTT[0].Coeffs, ctNTT[1].Coeffs},
	}

	now = time.Now()
	vf := verifier.Verify(&publicAssignment, pf)
	fmt.Println("Verifier time:", time.Since(now))
	fmt.Println("Verification result:", vf)

	fmt.Println("Estimated Size:", prover.JindoParams.Size()/math.Exp2(23), "MB")
}
