// Code generated by gnark-crypto/generator. DO NOT EDIT.
#include "textflag.h"
#include "funcdata.h"
#include "go_asm.h"

// butterfly(a, b *Element)
// a, b = a+b, a-b
TEXT ·Butterfly(SB), NOFRAME|NOSPLIT, $0-16
	LDP  x+0(FP), (R8, R9)
	LDP  0(R8), (R0, R1)
	LDP  0(R9), (R2, R3)
	ADDS R0, R2, R4
	ADC  R1, R3, R5
	SUBS R2, R0, R2
	SBCS R3, R1, R3
	LDP  ·qElement+0(SB), (R0, R1)
	CSEL CS, ZR, R0, R6
	CSEL CS, ZR, R1, R7

	// add q if underflow, 0 if not
	ADDS R2, R6, R2
	ADC  R3, R7, R3
	STP  (R2, R3), 0(R9)

	// q = t - q
	SUBS R0, R4, R0
	SBCS R1, R5, R1

	// if no borrow, return q, else return t
	CSEL CS, R0, R4, R4
	CSEL CS, R1, R5, R5
	STP  (R4, R5), 0(R8)
	RET

// mul(res, x, y *Element)
// Algorithm 2 of Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS
// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521
TEXT ·mul(SB), NOFRAME|NOSPLIT, $0-24
#define DIVSHIFT() \
	MUL   R9, R8, R0  \
	ADDS  R0, R4, R4  \
	MUL   R10, R8, R0 \
	ADCS  R0, R5, R5  \
	ADC   R6, ZR, R6  \
	UMULH R9, R8, R0  \
	ADDS  R0, R5, R4  \
	UMULH R10, R8, R0 \
	ADCS  R0, R6, R5  \

#define MUL_WORD_N() \
	MUL   R2, R1, R0 \
	ADDS  R0, R4, R4 \
	MUL   R4, R7, R8 \
	MUL   R3, R1, R0 \
	ADCS  R0, R5, R5 \
	ADC   ZR, ZR, R6 \
	UMULH R2, R1, R0 \
	ADDS  R0, R5, R5 \
	UMULH R3, R1, R0 \
	ADC   R0, R6, R6 \
	DIVSHIFT()       \

#define MUL_WORD_0() \
	MUL   R2, R1, R4 \
	MUL   R3, R1, R5 \
	UMULH R2, R1, R0 \
	ADDS  R0, R5, R5 \
	UMULH R3, R1, R0 \
	ADC   R0, ZR, R6 \
	MUL   R4, R7, R8 \
	DIVSHIFT()       \

	MOVD y+16(FP), R11
	MOVD x+8(FP), R0
	LDP  0(R0), (R2, R3)
	MOVD 0(R11), R1
	MOVD $const_qInvNeg, R7
	LDP  ·qElement+0(SB), (R9, R10)
	MUL_WORD_0()
	MOVD 8(R11), R1
	MUL_WORD_N()

	// reduce if necessary
	SUBS R9, R4, R9
	SBCS R10, R5, R10
	MOVD res+0(FP), R0
	CSEL CS, R9, R4, R4
	CSEL CS, R10, R5, R5
	STP  (R4, R5), 0(R0)
	RET

// reduce(res *Element)
TEXT ·reduce(SB), NOFRAME|NOSPLIT, $0-8
	LDP  ·qElement+0(SB), (R2, R3)
	MOVD res+0(FP), R4
	LDP  0(R4), (R0, R1)

	// q = t - q
	SUBS R2, R0, R2
	SBCS R3, R1, R3

	// if no borrow, return q, else return t
	CSEL CS, R2, R0, R0
	CSEL CS, R3, R1, R1
	STP  (R0, R1), 0(R4)
	RET
