// Code generated by gnark-crypto/generator. DO NOT EDIT.
#include "textflag.h"
#include "funcdata.h"
#include "go_asm.h"

#define REDUCE(ra0, ra1, rb0, rb1, q0, q1) \
	MOVQ    ra0, rb0; \
	SUBQ    q0, ra0;  \
	MOVQ    ra1, rb1; \
	SBBQ    q1, ra1;  \
	CMOVQCS rb0, ra0; \
	CMOVQCS rb1, ra1; \

TEXT ·reduce(SB), NOSPLIT, $0-8
	MOVQ res+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	RET

// MulBy3(x *Element)
TEXT ·MulBy3(SB), NOSPLIT, $0-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX

	// reduce element(DX,CX) using temp registers (DI,R8)
	REDUCE(DX,CX,DI,R8,·qElement+0(SB),·qElement+8(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	RET

// MulBy5(x *Element)
TEXT ·MulBy5(SB), NOSPLIT, $0-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (DI,R8)
	REDUCE(DX,CX,DI,R8,·qElement+0(SB),·qElement+8(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX

	// reduce element(DX,CX) using temp registers (R9,R10)
	REDUCE(DX,CX,R9,R10,·qElement+0(SB),·qElement+8(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	RET

// MulBy13(x *Element)
TEXT ·MulBy13(SB), NOSPLIT, $0-8
	MOVQ x+0(FP), AX
	MOVQ 0(AX), DX
	MOVQ 8(AX), CX
	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (DI,R8)
	REDUCE(DX,CX,DI,R8,·qElement+0(SB),·qElement+8(SB))

	MOVQ DX, DI
	MOVQ CX, R8
	ADDQ DX, DX
	ADCQ CX, CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	ADDQ DI, DX
	ADCQ R8, CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	ADDQ 0(AX), DX
	ADCQ 8(AX), CX

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	MOVQ DX, 0(AX)
	MOVQ CX, 8(AX)
	RET

// Butterfly(a, b *Element) sets a = a + b; b = a - b
TEXT ·Butterfly(SB), NOSPLIT, $0-16
	MOVQ    a+0(FP), R15
	MOVQ    0(R15), DX
	MOVQ    8(R15), CX
	MOVQ    DX, BX
	MOVQ    CX, SI
	XORQ    R15, R15
	MOVQ    b+8(FP), AX
	ADDQ    0(AX), DX
	ADCQ    8(AX), CX
	SUBQ    0(AX), BX
	SBBQ    8(AX), SI
	MOVQ    $const_q0, DI
	MOVQ    $const_q1, R8
	CMOVQCC R15, DI
	CMOVQCC R15, R8
	ADDQ    DI, BX
	ADCQ    R8, SI
	MOVQ    BX, 0(AX)
	MOVQ    SI, 8(AX)

	// reduce element(DX,CX) using temp registers (BX,SI)
	REDUCE(DX,CX,BX,SI,·qElement+0(SB),·qElement+8(SB))

	MOVQ a+0(FP), R15
	MOVQ DX, 0(R15)
	MOVQ CX, 8(R15)
	RET

// mul(res, x, y *Element)
TEXT ·mul(SB), $24-24

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521
	// See github.com/Consensys/gnark-crypto/field/generator for more comments.

	NO_LOCAL_POINTERS
	CMPB ·supportAdx(SB), $1
	JNE  noAdx_1
	MOVQ x+8(FP), CX

	// x[0] -> BX
	// x[1] -> SI
	MOVQ 0(CX), BX
	MOVQ 8(CX), SI
	MOVQ y+16(FP), DI

	// A -> BP
	// t[0] -> R14
	// t[1] -> R13
#define MACC(in0, in1, in2) \
	ADCXQ in0, in1     \
	MULXQ in2, AX, in0 \
	ADOXQ AX, in1      \

#define DIV_SHIFT() \
	MOVQ  $const_qInvNeg, DX        \
	IMULQ R14, DX                   \
	XORQ  AX, AX                    \
	MULXQ ·qElement+0(SB), AX, R8   \
	ADCXQ R14, AX                   \
	MOVQ  R8, R14                   \
	MACC(R13, R14, ·qElement+8(SB)) \
	MOVQ  $0, AX                    \
	ADCXQ AX, R13                   \
	ADOXQ BP, R13                   \

#define MUL_WORD_0() \
	XORQ  AX, AX       \
	MULXQ BX, R14, R13 \
	MULXQ SI, AX, BP   \
	ADOXQ AX, R13      \
	MOVQ  $0, AX       \
	ADOXQ AX, BP       \
	DIV_SHIFT()        \

#define MUL_WORD_N() \
	XORQ  AX, AX      \
	MULXQ BX, AX, BP  \
	ADOXQ AX, R14     \
	MACC(BP, R13, SI) \
	MOVQ  $0, AX      \
	ADCXQ AX, BP      \
	ADOXQ AX, BP      \
	DIV_SHIFT()       \

	// mul body
	MOVQ 0(DI), DX
	MUL_WORD_0()
	MOVQ 8(DI), DX
	MUL_WORD_N()

	// reduce element(R14,R13) using temp registers (R9,R10)
	REDUCE(R14,R13,R9,R10,·qElement+0(SB),·qElement+8(SB))

	MOVQ res+0(FP), AX
	MOVQ R14, 0(AX)
	MOVQ R13, 8(AX)
	RET

noAdx_1:
	MOVQ res+0(FP), AX
	MOVQ AX, (SP)
	MOVQ x+8(FP), AX
	MOVQ AX, 8(SP)
	MOVQ y+16(FP), AX
	MOVQ AX, 16(SP)
	CALL ·_mulGeneric(SB)
	RET

TEXT ·fromMont(SB), $8-8
	NO_LOCAL_POINTERS

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521
	// when y = 1 we have:
	// for i=0 to N-1
	// 		t[i] = x[i]
	// for i=0 to N-1
	// 		m := t[0]*q'[0] mod W
	// 		C,_ := t[0] + m*q[0]
	// 		for j=1 to N-1
	// 		    (C,t[j-1]) := t[j] + m*q[j] + C
	// 		t[N-1] = C
	CMPB ·supportAdx(SB), $1
	JNE  noAdx_2
	MOVQ res+0(FP), DX
	MOVQ 0(DX), R13
	MOVQ 8(DX), R14
	XORQ DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13
	MOVQ  $0, AX
	ADCXQ AX, R14
	ADOXQ AX, R14
	XORQ  DX, DX

	// m := t[0]*q'[0] mod W
	MOVQ  $const_qInvNeg, DX
	IMULQ R13, DX
	XORQ  AX, AX

	// C,_ := t[0] + m*q[0]
	MULXQ ·qElement+0(SB), AX, BP
	ADCXQ R13, AX
	MOVQ  BP, R13

	// (C,t[0]) := t[1] + m*q[1] + C
	ADCXQ R14, R13
	MULXQ ·qElement+8(SB), AX, R14
	ADOXQ AX, R13
	MOVQ  $0, AX
	ADCXQ AX, R14
	ADOXQ AX, R14

	// reduce element(R13,R14) using temp registers (CX,BX)
	REDUCE(R13,R14,CX,BX,·qElement+0(SB),·qElement+8(SB))

	MOVQ res+0(FP), AX
	MOVQ R13, 0(AX)
	MOVQ R14, 8(AX)
	RET

noAdx_2:
	MOVQ res+0(FP), AX
	MOVQ AX, (SP)
	CALL ·_fromMontGeneric(SB)
	RET
