//go:build purego || (!amd64 && !arm64)

// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package zp110

import "math/bits"

// MulBy3 x *= 3 (mod q)
func MulBy3(x *Uint) {
	_x := *x
	x.Double(x).Add(x, &_x)
}

// MulBy5 x *= 5 (mod q)
func MulBy5(x *Uint) {
	_x := *x
	x.Double(x).Double(x).Add(x, &_x)
}

// MulBy13 x *= 13 (mod q)
func MulBy13(x *Uint) {
	var y = Uint{
		14781150427581278322,
		7304965095100,
	}
	x.Mul(x, &y)
}

func fromMont(z *Uint) {
	_fromMontGeneric(z)
}

func reduce(z *Uint) {
	_reduceGeneric(z)
}

// Mul z = x * y (mod q)
//
// x and y must be less than q
func (z *Uint) Mul(x, y *Uint) *Uint {

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521

	var t0, t1 uint64
	var u0, u1 uint64
	{
		var c0, c1, c2 uint64
		v := x[0]
		u0, t0 = bits.Mul64(v, y[0])
		u1, t1 = bits.Mul64(v, y[1])
		t1, c0 = bits.Add64(u0, t1, 0)
		c2, _ = bits.Add64(u1, 0, c0)

		m := qInvNeg * t0

		u0, c1 = bits.Mul64(m, q0)
		_, c0 = bits.Add64(t0, c1, 0)
		u1, c1 = bits.Mul64(m, q1)

		t0, c0 = bits.Add64(0, c1, c0)
		u1, _ = bits.Add64(u1, 0, c0)
		t0, c0 = bits.Add64(u0, t0, 0)
		c2, _ = bits.Add64(c2, 0, c0)
		t0, c0 = bits.Add64(t1, t0, 0)
		t1, _ = bits.Add64(u1, c2, c0)

	}
	{
		var c0, c1, c2 uint64
		v := x[1]
		u0, c1 = bits.Mul64(v, y[0])
		t0, c0 = bits.Add64(c1, t0, 0)
		u1, c1 = bits.Mul64(v, y[1])
		t1, c0 = bits.Add64(c1, t1, c0)

		c2, _ = bits.Add64(0, 0, c0)
		t1, c0 = bits.Add64(u0, t1, 0)
		c2, _ = bits.Add64(u1, c2, c0)

		m := qInvNeg * t0

		u0, c1 = bits.Mul64(m, q0)
		_, c0 = bits.Add64(t0, c1, 0)
		u1, c1 = bits.Mul64(m, q1)

		t0, c0 = bits.Add64(0, c1, c0)
		u1, _ = bits.Add64(u1, 0, c0)
		t0, c0 = bits.Add64(u0, t0, 0)
		c2, _ = bits.Add64(c2, 0, c0)
		t0, c0 = bits.Add64(t1, t0, 0)
		t1, _ = bits.Add64(u1, c2, c0)

	}
	z[0] = t0
	z[1] = t1

	// if z ⩾ q → z -= q
	if !z.smallerThanModulus() {
		var b uint64
		z[0], b = bits.Sub64(z[0], q0, 0)
		z[1], _ = bits.Sub64(z[1], q1, b)
	}
	return z
}

// Square z = x * x (mod q)
//
// x must be less than q
func (z *Uint) Square(x *Uint) *Uint {
	// see Mul for algorithm documentation

	var t0, t1 uint64
	var u0, u1 uint64
	{
		var c0, c1, c2 uint64
		v := x[0]
		u0, t0 = bits.Mul64(v, x[0])
		u1, t1 = bits.Mul64(v, x[1])
		t1, c0 = bits.Add64(u0, t1, 0)
		c2, _ = bits.Add64(u1, 0, c0)

		m := qInvNeg * t0

		u0, c1 = bits.Mul64(m, q0)
		_, c0 = bits.Add64(t0, c1, 0)
		u1, c1 = bits.Mul64(m, q1)

		t0, c0 = bits.Add64(0, c1, c0)
		u1, _ = bits.Add64(u1, 0, c0)
		t0, c0 = bits.Add64(u0, t0, 0)
		c2, _ = bits.Add64(c2, 0, c0)
		t0, c0 = bits.Add64(t1, t0, 0)
		t1, _ = bits.Add64(u1, c2, c0)

	}
	{
		var c0, c1, c2 uint64
		v := x[1]
		u0, c1 = bits.Mul64(v, x[0])
		t0, c0 = bits.Add64(c1, t0, 0)
		u1, c1 = bits.Mul64(v, x[1])
		t1, c0 = bits.Add64(c1, t1, c0)

		c2, _ = bits.Add64(0, 0, c0)
		t1, c0 = bits.Add64(u0, t1, 0)
		c2, _ = bits.Add64(u1, c2, c0)

		m := qInvNeg * t0

		u0, c1 = bits.Mul64(m, q0)
		_, c0 = bits.Add64(t0, c1, 0)
		u1, c1 = bits.Mul64(m, q1)

		t0, c0 = bits.Add64(0, c1, c0)
		u1, _ = bits.Add64(u1, 0, c0)
		t0, c0 = bits.Add64(u0, t0, 0)
		c2, _ = bits.Add64(c2, 0, c0)
		t0, c0 = bits.Add64(t1, t0, 0)
		t1, _ = bits.Add64(u1, c2, c0)

	}
	z[0] = t0
	z[1] = t1

	// if z ⩾ q → z -= q
	if !z.smallerThanModulus() {
		var b uint64
		z[0], b = bits.Sub64(z[0], q0, 0)
		z[1], _ = bits.Sub64(z[1], q1, b)
	}
	return z
}

// Butterfly sets
//
//	a = a + b (mod q)
//	b = a - b (mod q)
func Butterfly(a, b *Uint) {
	_butterflyGeneric(a, b)
}
