//go:build !purego

// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package zp110

import (
	"github.com/consensys/gnark-crypto/utils/cpu"
	_ "github.com/sp301415/ringo-snark/buckler/internal/zp110/asm/element_2w"
)

var supportAdx = cpu.SupportADX

//go:noescape
func MulBy3(x *Uint)

//go:noescape
func MulBy5(x *Uint)

//go:noescape
func MulBy13(x *Uint)

//go:noescape
func mul(res, x, y *Uint)

//go:noescape
func fromMont(res *Uint)

//go:noescape
func reduce(res *Uint)

// Butterfly sets
//
//	a = a + b (mod q)
//	b = a - b (mod q)
//
//go:noescape
func Butterfly(a, b *Uint)

// Mul z = x * y (mod q)
//
// x and y must be less than q
func (z *Uint) Mul(x, y *Uint) *Uint {

	// Algorithm 2 of "Faster Montgomery Multiplication and Multi-Scalar-Multiplication for SNARKS"
	// by Y. El Housni and G. Botrel https://doi.org/10.46586/tches.v2023.i3.504-521

	mul(z, x, y)
	return z
}

// Square z = x * x (mod q)
//
// x must be less than q
func (z *Uint) Square(x *Uint) *Uint {
	// see Mul for doc.
	mul(z, x, x)
	return z
}
