// Code generated by command: go run asmgen.go -ntt -out ../../math/crt/asm_ntt_amd64.s -stubs ../../math/crt/asm_ntt_stub_amd64.go -pkg=crt. DO NOT EDIT.

//go:build amd64 && !purego

package crt

//go:noescape
func fwdNTTInPlacePow2BaseUnrollAVX512IFMA(coeffs []uint64, tw []uint64, twS []uint64, q uint64, idx uint64, N uint64, l uint64)

//go:noescape
func fwdNTTInPlacePow2StrideUnrollAVX512IFMA(coeffs []uint64, w uint64, wS uint64, q uint64, idx uint64, t uint64)

//go:noescape
func invNTTInPlacePow2BaseUnrollAVX512IFMA(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64, idx uint64, N uint64, l uint64)

//go:noescape
func invNTTInPlacePow2StrideUnrollAVX512IFMA(coeffs []uint64, w uint64, wS uint64, q uint64, idx uint64, t uint64)

//go:noescape
func fwdNTTInPlacePow2UnrollAVX512(coeffs []uint64, tw []uint64, twS []uint64, q uint64)

//go:noescape
func invNTTInPlacePow2UnrollAVX512(coeffs []uint64, twInv []uint64, twInvS []uint64, q uint64)

//go:noescape
func reduce4QAVX512IFMA(coeffs []uint64, q uint64)
