// Package bignum implements various utility functions regarding numeric types.
package bignum

import "math/big"

// Uint is an interface of elements in bigpoly.
// This captures the code generated by gnark-crypto/goff.
type Uint[E any] interface {
	New() E
	Set(E) E
	SetBytes([]byte) E
	SetInt64(int64) E
	SetUint64(uint64) E
	MustSetRandom() E
	Slice([]uint64)

	BigInt(res *big.Int) *big.Int
	SetBigInt(v *big.Int) E

	Marshal() []byte
	Unmarshal([]byte)

	Limb() int

	Add(x0, x1 E) E
	Sub(x0, x1 E) E
	Neg(x E) E
	Mul(x0, x1 E) E
	Inverse(x E) E
	Cmp(x E) int
}

// Exp computes x^e.
func Exp[E Uint[E]](x E, e uint64) E {
	var r E
	r = r.New().SetUint64(1)
	t := x.New().Set(x)
	for e > 0 {
		if e&1 == 1 {
			r.Mul(r, t)
		}
		t.Mul(t, t)
		e >>= 1
	}
	return r
}
