// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

// Package zp880 contains field arithmetic operations for modulus = 0xadb1a1...000001.
//
// The API is similar to math/big (big.Int), but the operations are significantly faster (up to 20x).
//
// Additionally zp880.Vector offers an API to manipulate []Uint.
//
// The modulus is hardcoded in all the operations.
//
// Field elements are represented as an array, and assumed to be in Montgomery form in all methods:
//
//	type Uint [14]uint64
//
// # Usage
//
// Example API signature:
//
//	// Mul z = x * y (mod q)
//	func (z *Element) Mul(x, y *Element) *Element
//
// and can be used like so:
//
//	var a, b Element
//	a.SetUint64(2)
//	b.SetString("984896738")
//	a.Mul(a, b)
//	a.Sub(a, a)
//	 .Add(a, b)
//	 .Inv(a)
//	b.Exp(b, new(big.Int).SetUint64(42))
//
// Modulus q =
//
//	q[base10] = 5469412841907964198432938302506237735287051881434643508826449968632352984287023846502526837844914603106459954915108330288646961703720089438556856532005861944780660712982129505199218219085462091631139392493379725384201280060606557464931314170434947966767177238839297
//	q[base16] = 0xadb1a158082ce7292e2d54b5f11f6f03072c436c277678ef6ece3e84751efd2246f2d3c79fcb5275fcec066fdcfef25a72052730b746933929f1a4492f989ef73e5a0f130e1cef350ab4c97631edaf1f19f10016f19c12a267be26b56b765f38ca6ee20750010000000000000001
//
// # Warning
//
// There is no security guarantees such as constant time implementation or side-channel attack resistance.
// This code is provided as-is. Partially audited, see https://github.com/Consensys/gnark/tree/master/audits
// for more details.
package zp880
