//go:build  !purego

// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

// We include the hash to force the Go compiler to recompile: 16489743580729284386
#include "asm/element_7w/element_7w_amd64.s"

