// Package num implements various utility functions regarding numeric types.
package num

import "math/big"

// Uint is an interface of elements in bigpoly.
// This captures the code generated by gnark-crypto/goff.
type Uint[E any] interface {
	New() E
	Set(E) E
	SetBytes([]byte) E
	SetInt64(int64) E
	SetUint64(uint64) E
	MustSetRandom() E
	Slice([]uint64)

	BigInt(res *big.Int) *big.Int
	SetBigInt(v *big.Int) E

	Marshal() []byte
	Unmarshal([]byte)

	Limb() int

	Add(x0, x1 E) E
	Sub(x0, x1 E) E
	Neg(x E) E
	Mul(x0, x1 E) E
	Inverse(x E) E
	Cmp(x E) int
}

// IsPowerOfTwo returns true if n is a power of two.
func IsPowerOfTwo(n int) bool {
	return n > 0 && (n&(n-1)) == 0
}

// ModInverse returns the modular inverse of x modulo m.
// Output is always positive.
// Panics if x and m are not coprime.
func ModInverse(x, m uint64) uint64 {
	x %= m

	a, b := x, m
	u, v := uint64(1), uint64(0)
	for b != 0 {
		q := a / b
		a, b = b, a-q*b
		u, v = v, u-q*v
	}

	if a != 1 {
		panic("modular inverse does not exist")
	}

	return u % m
}

// ModExp returns x^y mod q.
func ModExp(x, y, q uint64) uint64 {
	r := uint64(1)
	x %= q
	for y > 0 {
		if y&1 == 1 {
			r = (r * x) % q
		}
		x = (x * x) % q
		y >>= 1
	}
	return r
}

// ExpE computes x^e.
func ExpE[E Uint[E]](x E, e uint64) E {
	var r E
	r = r.New().SetUint64(1)
	t := x.New().Set(x)
	for e > 0 {
		if e&1 == 1 {
			r.Mul(r, t)
		}
		t.Mul(t, t)
		e >>= 1
	}
	return r
}

// BitReverseInPlace reorders v into bit-reversal order in-place.
func BitReverseInPlace[T any](v []T) {
	var bit, j int
	for i := 1; i < len(v); i++ {
		bit = len(v) >> 1
		for j >= bit {
			j -= bit
			bit >>= 1
		}
		j += bit
		if i < j {
			v[i], v[j] = v[j], v[i]
		}
	}
}
