//go:build !purego

// Copyright 2020-2026 Consensys Software Inc.
// Licensed under the Apache License, Version 2.0. See the LICENSE file for details.

// Code generated by consensys/gnark-crypto DO NOT EDIT

package zp

import (
	_ "github.com/sp301415/ringo-snark/jindo/internal/zp/asm/element_4w"
)

// Butterfly sets
//
//	a = a + b (mod q)
//	b = a - b (mod q)
//
//go:noescape
func Butterfly(a, b *Uint)

//go:noescape
func mul(res, x, y *Uint)

// Mul z = x * y (mod q)
//
// x and y must be less than q
func (z *Uint) Mul(x, y *Uint) *Uint {
	mul(z, x, y)
	return z
}

// Square z = x * x (mod q)
//
// x must be less than q
func (z *Uint) Square(x *Uint) *Uint {
	// see Mul for doc.
	mul(z, x, x)
	return z
}

// MulBy3 x *= 3 (mod q)
func MulBy3(x *Uint) {
	_x := *x
	x.Double(x).Add(x, &_x)
}

// MulBy5 x *= 5 (mod q)
func MulBy5(x *Uint) {
	_x := *x
	x.Double(x).Double(x).Add(x, &_x)
}

// MulBy13 x *= 13 (mod q)
func MulBy13(x *Uint) {
	var y = Uint{
		18446744073709551567,
		13060621202776610126,
		17977528907282356895,
		3059542435078888372,
	}
	x.Mul(x, &y)
}

func fromMont(z *Uint) {
	_fromMontGeneric(z)
}

//go:noescape
func reduce(res *Uint)
